runtime: php55
api_version: 38
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: www/\1
  upload: www/.+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.(css|js|php|html))$
  script: www/\1
